### ISSUE TITLE
Commit "a", Gawr Gura?

### ISSUE THREAD

**Issue by ericc-ch** [Frastio10/digital-marketing#1]
Chumbuds?

**Comment by Frastio10** [comment]
> Chumbuds?

Obviously, a huge fan here.


jk btw. i was just rushing to upload this shit out. lol

**Comment by Frastio10** [comment]
Obviously, a big fan here.

jk btw. i was just rushing to upload this shit out. lol

**Comment by Frastio10** [comment]
> Chumbuds?

Obviously, a big fan here.

jk btw. i was just rushing to upload this shit out. lol
